### ISSUE TITLE
video_tool.py render: lost data when capturing frames  

### ISSUE THREAD

**Issue by BGI-biotools** [google/neuroglancer#341] opened 2021-09-15 09:39 UTC
I am trying to save the video using this script and find that there is data loss. Tuning '-- Prefetch' parameter  has improved, but not completely resolved. Lines 41-43 of the script are described below (The `render` command is used to render an existing script to a sequence of PNG images.   Frames are captured only once all data has been loaded; because of this, rendering can be slow.) . I feel that the situation we encountered is not consistent with the description, so I would like to ask you to help confirm what is the problem, thank you very much. 

default parameter
![0000000](https://user-images.githubusercontent.com/66717871/133409835-74ad2311-165c-42bb-8dad-9a0c94eb0cc1.png)

-- Prefetch=4
![0000000](https://user-images.githubusercontent.com/66717871/133409769-25619056-576c-43b0-acdd-ddf05a95ff67.png)
![0000007](https://user-images.githubusercontent.com/66717871/133409790-538399d5-4e31-4ee6-aa99-f12cc0a5e08d.png)

**Comment by jbms** [comment] 2021-09-15 13:59
It sounds like there may be a bug in the logic for checking that all data has loaded.  Can you describe which data sources / types of layers you are using?

Also, if you are able to share an example that reproduces the problem that would be helpful.

**Comment by BGI-biotools** [comment] 2021-09-16 01:40
The data is made up of two parts, one is precomputed annotation, and the other is a .obj data . We got 96 screenshots, 24 of which were lacked  the external mesh.Both data are stored on our local machine. It cannot be shared temporarily due to some reasons,I'm sorry about that.

**Comment by jbms** [comment] 2021-09-16 03:08
It turns out the implementation of the function responsible for checking if all data was ready was missing for the type of layer used for `.obj` meshes.  That is now fixed.

**Closed** 2021-09-16 03:08 UTC
