### ISSUE TITLE
Feature Request: Viewing Multiscale Zarr

### ISSUE THREAD

**Issue by sharmishtaa** [google/neuroglancer#396] opened 2022-06-09 20:11 UTC
We are beginning to consider OME zarr as a potential data format for large scale imaging pipelines. However, at the moment we can't view multiscale zarr with neuroglancer. It would be incredibly useful and have a great impact if this capability is implemented.
Thank you!

**Comment by jbms** [comment] 2022-06-15 00:39
This is a duplicate of #360.

**Closed by jbms** 2022-06-15 00:39 UTC
