### ISSUE TITLE
Parts of low resolution chunks loading when they shouldn't?

### ISSUE THREAD

**Issue by davidackerman** [google/neuroglancer#307] opened 2021-05-10 14:23 UTC
I mentioned this in a thread regarding other another issue, but figured it made more sense to create a separate issue about it:

When I have multiresolution meshes and am looking at high resolutions, parts of the lower res meshes load at chunk borders. This becomes more noticeable the smaller the chunks are (see below where the long strip and floating hexagons are from a different resolution). There doesn't appear to be an issue with Z-curve order and when I download the chunks directly and open them in a mesh viewer, the mesh at each resolution looks correct. This is what leads me to suspect that something is going on with how chunks are actually loaded. Or is this something on my end?

Here is the [multiresolution mesh data](https://drive.google.com/drive/folders/16oMQFEWWQqFC9Bp5NsGLS26wc-bZok1H?usp=sharing) I used. 
Thanks!
![image](https://user-images.githubusercontent.com/19193291/117672658-0ac7f300-b178-11eb-8dbf-1bebd11c8cd9.png)
![image](https://user-images.githubusercontent.com/19193291/117674637-d81efa00-b179-11eb-98a7-0c0118f0a6ee.png)

**Comment by jbms** [comment] 2021-05-11 19:46
I believe the problem is that your low-resolution mesh fragments are not properly partitioned according to the 8 subchunks into which they are partitioned.

For lod > 0, neuroglancer partitions the triangles of each fragment into 8 sub-fragments.  That is necessary to allow rendering just part of the coarser fragment when finer-lod fragments are rendered.

There are two issues:

1. Currently, if a finer lod fragment does not exist at all, Neuroglancer will still attempt to render the corresponding sub-fragment of the coarser lod as a replacement.  That should probably be fixed, though in most cases it shouldn't matter.
2. For simplicity, Neuroglancer does not attempt to split individual triangles.  Instead, Neuroglancer assumes the mesh was constructed in such a way as to ensure no triangles cross a sub-fragment boundary.  If a triangle happens to cross a sub-fragment boundary (i.e. cannot be correctly assigned to any sub-fragment) then currently Neuroglancer just assigns it to be part of sub fragment 0, which corresponds to the lower half of x, y, and z.  This combined with the first issue results in some of your triangles that cross the boundary being rendered when they should not.  Fixing your meshes to ensure they can be partitioned should solve this problem.

**Comment by davidackerman** [comment] 2021-05-12 00:00
You're right, that fixed it! Thanks so much. I somehow missed the line in the mesh description about the requirement that lod>0 meshes must be partitioned by 2x2x2 grid. Sorry about all that!

**Comment by davidackerman** [comment] 2021-05-13 04:02
Really sorry to keep bringing this issue up. I thought I had solved it but turns out I didn't quite. The issue I am having stems from this equation:

```grid_origin[j] +
vertex_offsets[lod,j] +
chunk_shape[j] * (2**lod) * (fragmentPosition[j] +
                             x / ((2**vertex_quantization_bits)-1))
```

I'm wondering, for partitioning lod>0 into 2x2x2 grids, what grid coordinates should be used? For example, if my lod=0 chunks have a shape of 32x32x32, then lod=1 chunks would have a shape of 64x64x64. If vertex_quantization_bits=10, then the denominator above would be 1023. But since `x` would be an int, there would be no value that could be plugged in to get 32 when lod=1, and so no way to divide lod=1 into 2x2x2 chunks that align with lod=0 chunks. Is this correct? Are there approximations that need to be made? Apologies if I am completely miscalculating or missing something.

**Comment by davidackerman** [comment] 2021-05-13 20:03
Turns out I was getting a rounding error where a vertex coordinate that should have been quantized to a value of 512 was being set to 511. Seems like it had to do with floating point rounding errors. I was basing my quantizer on [this](https://github.com/google/neuroglancer/issues/266#issuecomment-739601142), but wound up fixing it (I think) by pulling out `+ 0.5 / scale[i]` in `offset`. My quantizer is below (for my purposes I set the mesh origin to always be (0,0,0) and so have eliminated it from the quantizer.
```c
  Quantizer(coords_t const & fragment_shape, coords_t const & fragment_origin, int num_quantization_bits) {
        for (int i = 0; i < 3; ++i) {
            upper_bound[i] =
                static_cast<float>(std::numeric_limits<uint32_t>::max() >>
                                    (sizeof(uint32_t) * 8 - num_quantization_bits));
            scale[i] = upper_bound[i] / static_cast<float>(fragment_shape[i]);
            offset[i] = fragment_origin[i] ;//mesh_origin[i] - fragment_origin[i] + 0.5 / scale[i];
        }
  }

  // Maps an input vertex position `v_pos`.
  std::array<uint32_t, 3> operator()(std::array<float, 3>& v_pos) {
    for (int i = 0; i < 3; ++i) {
      output[i] = static_cast<uint32_t>(std::min(
          //might need to further fix this due to rounding artifacts which set eg a value to 511 when it should be 512. that is why i moved scale out here
          upper_bound[i], std::max(0.0f, (v_pos[i] - offset[i]) * scale[i] + 0.5f))); // Add 0.5 to round to nearest rather than round down.
    }
    return output;
  }
```

**Comment by davidackerman** [comment] 2021-05-15 12:50
@jbms I fixed the above issues as mentioned, but I may have run into a potential bug, or at least behavior I didn't know would happen. 

Currently I do not include any non-mesh-containing fragments in my index file. However, in the below example (top) that causes part of a low res fragment to persist no matter the resolution I set. I believe this is because that subfragment at lod=3 has empty fragment counterparts at lods 2, 1 and 0, and so it is never replaced by a higher res counterpart? When I include the empty fragment in the index file for lod=2, the issue goes away (see bottom panel below). In short, I could fix the behavior by including empty fragments in the index file. Is this the expected behavior? The corresponding data can be found [here](https://drive.google.com/drive/folders/1zeXkGS7I8zVEXQOAn9H33GcPl_6FdycV?usp=sharing); two index files are provided, one that excludes the empty fragment (which causes the bug) and one that includes the empty fragment (which fixes the bug).

![image](https://user-images.githubusercontent.com/19193291/118361287-b0081000-b558-11eb-9e88-f9228c34910b.png)

**Comment by jbms** [comment] 2021-05-15 15:42
Yes, you need to add empty fragments to avoid this.  However, the fragment can be listed as zero bytes in the manifest --- Neuroglancer interprets that as an empty fragment.  You don't need to create a valid draco-encoded mesh for the empty fragments.

**Closed** 2021-05-15 20:51 UTC
