### ISSUE TITLE
Regression in DVID support

### ISSUE THREAD

**Issue by pgunn** [google/neuroglancer#279] opened 2021-01-20 21:01 UTC
https://github.com/google/neuroglancer/commit/2be319996f547ab70bcbe259bb6955e7f58125bc broke support for DVID datasources that don't have a running token server working. Please consider a flag, when adding DVID data sources, to disable the requirement for tokenized access.

@tingzhao

**Comment by jbms** [comment] 2021-01-21 01:05
Thanks for reporting.  I'm working on a fix for this so that servers that don't require authentication just work as well without any special flag.

**Comment by jbms** [comment] 2021-01-21 02:38
I think this is fixed by 4d974858313aad7eb775bb9dbc161c3a8428af56.  However, it is possible that I accidentally broke authenticated DVID access, since I don't know of a server to test against.  Please let me know if that is not working.

**Comment by pgunn** [comment] 2021-01-21 02:46
Do you control https://neuroglancer-demo.appspot.com/  ? That's the neuroglancer instance we've been using (I have never actually built a local install of it)

**Comment by jbms** [comment] 2021-01-21 02:52
Yes, that is deployed automatically from the master branch of this repository, but it takes a few minutes.  The change appears to be deployed now:

https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B3456.5%2C2976.5%2C4480.5%5D%2C%22crossSectionScale%22:1%2C%22projectionScale%22:8192%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%22dvid://https://flyem.dvid.io/2b6d75f1c6e348ce945e1a66eb2f6bf3/groundtruth%22%2C%22tab%22:%22source%22%2C%22name%22:%22groundtruth%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22groundtruth%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%7D

**Comment by pgunn** [comment] 2021-01-21 03:02
That's getting me an annoying CORS error now, but at least it's not requesting a token anymore. I'll have to futz with the CORS stuff on our DVID server to make sure it's really fixed.

I'm guessing there must be a reason the referrer policy got a lot stricter recently?

**Comment by jbms** [comment] 2021-01-21 03:07
I think 2be3199 may have affected the CORS behavior, not sure it was intentional.  I don't regularly use the dvid backend myself, and I don't have a full understanding of how it is used at Janelia, so when reviewing changes it is difficult for me to know the impact. If you or someone else from Janelia would like to describe the different ways you use this backend or what you'd like to accomplish, I can try to make some recommendations.

**Comment by pgunn** [comment] 2021-01-21 03:15
Dropped you an email; I don't want to expose our DVID URL to the internet.

**Comment by tingzhao** [comment] 2021-01-21 14:38
The CORS error might be caused by a change in DVID because we have the same problem here. DVID has changed its CORS policy since a certain version. @DocSavage can comment on this. We usually run our own neuroglancer server to access DVID data on the same domain.

**Comment by DocSavage** [comment] 2021-01-21 15:22
Pat, could you email me with your current DVID version so I can check if it's an issue on our end.  We have been modifying some things due to the public rollout of services and CORS issues.

**Comment by pgunn** [comment] 2021-01-21 15:43
@DocSavage Email sent.

I'm a little worried about needing to statically specify all allowed origins (as we have Catmaid now that we still use occasionally, want to use neuroglancer for some things, and have a few smaller things as well).

**Comment by jbms** [comment] 2021-01-21 16:16
@DocSavage Can you explain how authentication with DVID is supposed to work?

Currently, the Neuroglancer DVID datasource supports a number of different methods and fallbacks, but I'm not sure what different methods are actually used.

I suppose Pat would like completely unauthenticated access (which was how things worked before any authentication support was added): all requests are made without credentials and without cookies.  Currently the neuroglancer dvid datasource always attempts to send cookies if an https:// dvid server is specified, which requires a more complicated CORS configuration to work even just to ignore the cookies.

Neuroglancer also supports requesting an auth token from /api/server/token and then sending that as an Authentication header.  In that case cookies are not sent with requests, except to the initial /api/server/token endpoint.

Is both the cookie-based and token-based authentication required?

**Comment by DocSavage** [comment] 2021-01-21 17:27
@jbms From just the DVID perspective (and not other parts of the current FlyEM data services like the new Clio), currently there is an optional token-based (JWT) that can be configured as explained here:
https://github.com/janelia-flyem/dvid/blob/master/scripts/distro-files/config-full.toml#L51

It was designed to get this token from another service (flyem-services) via a cookie, but I'd like to make this more generic and am open to suggestions.  Part of this was rushed out to support some services we wanted to deploy.

CORS domains can be specified in the config TOML file as well:
https://github.com/janelia-flyem/dvid/blob/master/scripts/distro-files/config-full.toml#L27

**Comment by jbms** [comment] 2021-01-21 19:24
@DocSavage Does DVID ever rely on cookie-based authentication of individual requests, rather than token-based authentication?  Currently Neuroglancer supports that, but I'm wondering if that can be removed.

**Comment by DocSavage** [comment] 2021-01-21 19:31
@jbms DVID does not rely on cookie-based authentication of individual requests.  It does have a `/api/server/token` that contacts another service, checks the cookie, and then returns a JWT, but it's direct DVID <-> flyem service so don't see why I need neuroglancer to pass that along.

**Comment by jbms** [comment] 2021-01-21 23:44
Sending a cookie to /api/server/token is not a problem, in fact that is the simplest approach.

Is there some circumstance in which a different auth server needs to be used?  Ideally that  could be phased out.

**Comment by jbms** [comment] 2021-01-21 23:46
What I'm wondering about is this line (added by @tingzhao ): https://github.com/google/neuroglancer/blob/69f308ddcaa5c467ac669785d41178fa779352df/src/neuroglancer/datasource/dvid/api.ts#L136

Can that be removed?

**Comment by tingzhao** [comment] 2021-01-22 14:25
Yes, this can be removed. We're also updating our authentication strategy and this shouldn't be necessary in the future.

**Closed** 2021-01-22 17:39 UTC
