### ISSUE TITLE
Isolate child element in equivalence map

### ISSUE THREAD

**Issue by sheridana** [google/neuroglancer#355] opened 2021-11-12 21:53 UTC
It is possible to link a proofreading layer to a labels layer and use annotations to merge labels using an `EquivalenceMap()`. The parent label can then also be isolated and split from its children using the `isolate_element()` function. Is there an easy way to isolate a child label based on an intersecting annotation? It would be straight forward to do this on the underlying array, but it doesn't seem like there is an existing way to modify the state, like there is for the union.

A simple example with merging and then isolating a parent element:

![isolate](https://user-images.githubusercontent.com/29460471/141506072-7c194ba8-276f-43ac-968b-aec68c561461.png)

After merging, we can split the parent label (1) from its child (2) and then (2) from its child (3). The ideal behavior would be to isolate, for example, (3) directly from (1). It seems like the children are tracked directly because hovering over shows the equivalence, e.g 3 --> 2 | 2 --> 1, so is there a way to go backwards, and update the state?

Example code:

```py
import neuroglancer
import numpy as np
import webbrowser

neuroglancer.set_server_bind_address("0.0.0.0")

viewer = neuroglancer.Viewer()

data = np.arange(2*2, dtype=np.uint64).reshape(2,2)

dims = neuroglancer.CoordinateSpace(
    names=["x", "y"],
    units="m",
    scales=[1,]*2,
)

vol = neuroglancer.LocalVolume(data=data, dimensions=dims)

def union(s):
    segments = set()
    for segment in s.viewer_state.layers["anno"].annotations:
        if segment.segments:
            ids = [i for s in segment.segments for i in s if i != 0]
            segments.update(ids)

    with viewer.txn() as txn:
        for segment in segments:
            txn.layers["labels"].equivalences.union(max(segments), segment)
        txn.layers["anno"].annotations = None


def isolate(s):
    segments = set()
    for segment in s.viewer_state.layers["anno"].annotations:
        if segment.segments:
            ids = [i for s in segment.segments for i in s if i != 0]
            segments.update(ids)

    with viewer.txn() as txn:
        for segment in segments:
            txn.layers["labels"].equivalences.isolate_element(segment)
        txn.layers["anno"].annotations = None


with viewer.txn() as s:

    s.layers["labels"] = neuroglancer.SegmentationLayer(source=vol)

    s.layers["anno"] = neuroglancer.LocalAnnotationLayer(
        linked_segmentation_layer={"segments": "labels"}, dimensions=dims
    )

    s.layout = "xy"
    s.position = [1, 1]
    s.cross_section_scale = 0.005

viewer.actions.add("union", union)
viewer.actions.add("isolate", isolate)

with viewer.config_state.txn() as s:
    s.input_event_bindings.viewer["keyu"] = "union"
    s.input_event_bindings.viewer["keyi"] = "isolate"

url = str(viewer)
print(url)

try:
    webbrowser.open_new_tab(url)
except:
    webbrowser.open_new(url)
```

**Comment by jbms** [comment] 2021-11-12 22:03
Perhaps you can explain a bit more exactly what type of action you want?

Note that the Neuroglancer itself now contains slightly better support for dealing with local equivalences.  You can now perform split and merge actions directly in Neuroglancer, independently from the Python integration.  The splitting and merging is based on a spanning tree representation.

It is not currently documented, but here is how you can try it out:

1. Open the layer side panel for the segmentation layer that you want to reconstruct, e.g. by right clicking it in the layer bar.
2. Select the "Source" tab if not already selected.
3. At the bottom of the Source tab, there is a "+" button for adding a new data source.  Click that, then type "local://equivalences" and press enter.  Underneath the added data source "local segmentation graph" should be listed.
4. Select the "Seg" tab.
5. Note that "Merge" and "Split" are now listed at the top of the Seg tab.  While holding down the left mouse button to click the empty "[ ]" to the left of  "Merge", press a letter key a-z that you want to use for merging, such as "x".  Since you will have to hold down shift to use these keys, and will want to reserve your right hand for the mouse (assuming you use the mouse with your right hand), make sure to pick a key that is near the left shift key.  Likewise hold down the left mouse button over the empty "[ ]" to the left of "Split" and pick a different key, e.g. "s".  This will allow you to merge and split by holding down "shift+x" and "shift+s" respectively.
6. There is just one last key binding you should set up.  Select the "Render" tab.  While holding down the left mouse button to click on the empty "[ ]" next to "Base segment coloring", press another letter a-z, such as "c".
7. To merge segments, you first need to set the "anchor" segment to which all of your added segments will be merged.  To do this, make sure the desired anchor segment is selected (e.g. by double clicking it), then hold down shift+x and right click on the segment.  You can change the anchor segment at any time with shift+x rightclick.
8. Once you have set the anchor segment, you can merge segments to it by holding down shift+x, hovering the mouse over the segment you want to merge, and left clicking.  When you hold down shift+x, the display changes to show a preview of the merge that will be performed.  All selected segments are hidden, and the anchor segment as well as the segment you are currently hovering over are shown.  For example if you are picking the continuation segment in 2d, you can just hover over it while holding down shift+x and if you wait a second for it to load, it will be shown in 3d as well without needing to double click.
9. Once you have performed the merge, the new merged segment will all be shown in the same color.  If you press shift+c, though, that toggles base segment coloring, which allows you to see the base segments that make up an agglomerated segment.
10. If you make a mistake when merging, you can correct it by splitting.  This works similarly to merging: there is an anchor segment (same one used for merging), which you can set with shift+s rightclick.  Then while holding down shift+s, only the agglomerated anchor segment is shown.  If you hover over a portion of the agglomerated anchor segment, a preview of the split is shown, by using two separate colors to show the two parts that will result from the split.  You don't explicitly choose exactly where the split will occur.  Instead, Neuroglancer remembers the tree of merges that you performed, and always splits according to this same tree.  The split point within this tree is chosen so that the segment you hover over (the part to split off) is as small as possible.

And here is an example link:
[Example link](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B3.3e-8%2C%22m%22%5D%7D%2C%22position%22:%5B207739.421875%2C189675.109375%2C602.9854125976562%5D%2C%22crossSectionScale%22:0.1630621301322297%2C%22crossSectionDepth%22:-113.36185634656202%2C%22projectionOrientation%22:%5B0.048151347786188126%2C-0.7968328595161438%2C-0.5595887899398804%2C0.2227087914943695%5D%2C%22projectionScale%22:12718.324092663377%2C%22projectionDepth%22:-93.64863571737415%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210601/4nm_raw%22%2C%22tab%22:%22source%22%2C%22name%22:%224nm%20EM%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%7B%22url%22:%22precomputed://gs://h01-release/data/20210601/c3%22%2C%22subsources%22:%7B%22default%22:true%2C%22bounds%22:true%2C%22properties%22:true%2C%22mesh%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22local://equivalences%22%5D%2C%22toolBindings%22:%7B%22C%22:%22baseSegmentColoring%22%2C%22X%22:%22mergeSegments%22%2C%22S%22:%22splitSegments%22%7D%2C%22tab%22:%22segments%22%2C%22anchorSegment%22:%2222830606544%22%2C%22meshRenderScale%22:48.715170586137106%2C%22equivalences%22:%5B%5B%225260245133%22%2C%2214023619071%22%5D%2C%5B%2214023619071%22%2C%2222830606544%22%5D%5D%2C%22segments%22:%5B%225260245133%22%5D%2C%22name%22:%22c3%20segmentation%22%7D%5D%2C%22showSlices%22:false%2C%22prefetch%22:false%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22c3%20segmentation%22%7D%2C%22layout%22:%224panel%22%2C%22layerListPanel%22:%7B%22visible%22:true%7D%7D)

One caveat is that the EquivalenceMap class in the Python API is not yet updated to properly preserve or work with the spanning tree.  Instead, if you attempt to manipulate the equivalences using the Python API, the equivalences themselves will be correctly preserved, but the spanning tree will be lost, which means subsequent split actions won't work very well.

**Comment by sheridana** [comment] 2021-11-13 00:43
That's exactly what I had in mind, but a little more involved. Ideally I would be able to just remove a child element (i.e supervoxel) from a merged label when a point annotation intersects with the element. The rest of the merged children would remain merged. It would be good to be able to access this pythonically to wrap it in a lightweight callback. It is easy enough to do this with the merging right now, could you point me to the splitting code? Thank you!

**Comment by jbms** [comment] 2021-11-13 00:50
I'm not sure I understand what you are trying to accomplish differs from the existing EquivalenceMap.isolate_element method.

**Comment by sheridana** [comment] 2021-11-13 01:12
`isolate_element` seems to return the parent not the child, regardless of where a point is placed. maybe a 3d example is better:

we have two segments (parents) which each consist of 8 children:

<img width="1389" alt="Screen Shot 2021-11-12 at 5 03 28 PM" src="https://user-images.githubusercontent.com/29460471/141599840-8b5921e7-d048-401f-a955-b69165222955.png">

we accidentally merge the two together (yellow dots 4th child down in each segment):

<img width="1389" alt="Screen Shot 2021-11-12 at 5 03 41 PM" src="https://user-images.githubusercontent.com/29460471/141599848-b42667a2-f757-453b-8e4b-764b82a9d419.png">
<img width="1389" alt="Screen Shot 2021-11-12 at 5 03 44 PM" src="https://user-images.githubusercontent.com/29460471/141599850-c6b27021-8579-452a-82a9-c3ca3bdb4dcf.png">

Now we try to isolate the 4th element down in the left segment (yellow dot):

<img width="1389" alt="Screen Shot 2021-11-12 at 5 03 52 PM" src="https://user-images.githubusercontent.com/29460471/141599851-45586a63-e6f7-41b5-bf65-0c7fdb5de3b6.png">

we end up isolating the parent node (top element, left segment), regardless of where we place the node:

<img width="1389" alt="Screen Shot 2021-11-12 at 5 04 00 PM" src="https://user-images.githubusercontent.com/29460471/141599852-79b86491-bc91-437b-8a4d-647e1a0a3199.png">

but the ideal behavior would be to split away the 4th element:

<img width="1389" alt="Screen Shot 2021-11-12 at 5 11 48 PM" src="https://user-images.githubusercontent.com/29460471/141600097-a54deb34-c04f-426b-bfae-6edf890376e3.png">

**Comment by jbms** [comment] 2021-11-13 01:18
Oh, I see.  The issue is that when you create an annotation with a related segment, the id used is always the root segment id, not the base supervoxel id.  However, Python action callbacks can obtain the base supervoxel id from `ActionState.selected_values`.  In particular, for the segmentation layer if the mouse is over a mapped id, then the value will be a `SegmentIdMapEntry`.

**Comment by sheridana** [comment] 2021-11-13 07:29
Hmm that could work for removing a single element per callback, but I guess the problem is a case where > 1 element needs to be selected - since `selected_values` only knows the id under the mouse. The nice thing for the union case is that we know each segment to be merged: 

```py
for segment in s.viewer_state.layers["anno"].annotations:
        print(segment.segments)
```

but after merging, the only segment stored is the parent segment which can't give us the children. I guess a mapping could be created whenever merging (e.g 1 --> 2) which could then be used as a reverse lookup during a split (2 --> 1). If the mapping exists (i.e after a merge), it could be stored directly inside `annotations.segments` for each annotation. Is this something similar to the splitting in the example you sent?

**Comment by sheridana** [comment] 2021-11-14 20:24
Actually, isolating a single child element works fine in my case. So something like this would work for both parent and child:

```py
def isolate(s):

    with viewer.txn() as txn:
        equivalences = txn.layers["labels"].equivalences

        try:
            key = s.selected_values["labels"].value.key

            del equivalences._parents[key]
            del equivalences._weights[key]
            del equivalences._prev_next[key]
            del equivalences._min_values[key]

        except:
            key = s.selected_values["labels"].value
            equivalences.isolate_element(key)
```

**Closed** 2021-11-29 17:39 UTC
